name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: npm run build

      # 部署到github
      - name: Deploy to Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: build # 打包的内容放到build分支下
          folder: dist